### ISSUE TITLE
ConfirmDialog injection doesn't work in bundled version

### ISSUE THREAD

**Issue by Hawxy** [wobsoriano/vuetify-use-dialog#1]
Hello,
First of all, thanks for this package, I'm in the middle of an upgrade and this saved a bunch of time porting my vue 2 dialog/snackbar code over.

I'm seeing an issue whereby `ConfirmDialog` is unable to inject on mount, with the warning:
```
[Vue warn]: injection "Symbol(ConfirmDialogKey)" not found. 
  at <ConfirmDialog dialogProps=
```
Naturally this results in the dialog not working properly as the promise is never resolved.
If I vendor this package within my codebase the issue goes away, thus the issue is limited to the version distributed on npm.

**Comment by wobsoriano** [comment]
Fixed in v0.2.0.
