### ISSUE TITLE
snackbarProps and closeButtonProps should be merged with defaults

### ISSUE THREAD

**Issue by donalmurtagh** [wobsoriano/vuetify-use-dialog#12]
I've defined the following defaults for the snackbar props

```javascript
 app.use(VuetifyUseDialog, {
    snackbar: {
      theme: 'light',
      snackbarProps: {
        timeout: -1,
        location: 'top',
        color: 'success'
      },
      closeButtonProps: {
        variant: 'text'
      }
    }
  })
```

If I call `this.$toast({ text: 'Event updated'})` it works as expected. However, if I call
```
this.$toast({ text: 'Event updated', snackbarProps: { color: 'warning' } })
```

Then I expect the snackbarProps in this call to be merged with the defaults. In other words, the call above should be the same as
```
this.$toast({ text: 'Event updated', snackbarProps: { color: 'warning', timeout: -1, location: 'top' } })
```

But what actually happens is that all of the default snackbarProps are ignored, so the call above is effectively the same as
```
this.$toast({ text: 'Event updated', snackbarProps: { color: 'warning', timeout: 5000, location: 'bottom' } })
```

In order to get the behaviour I want, I have to explicitly call
```
this.$toast({ text: 'Event updated', snackbarProps: { color: 'warning', timeout: -1, location: 'top' } })
```

Would it be possible to merge the snackbarProps (and closeButtonProps) in the call with the defaults instead?

**Comment by wobsoriano** [comment]
That's interesting. I thought it will inherit the default options already
