### ISSUE TITLE
Error in console when using confirm

### ISSUE THREAD

**Issue by cxl-todd** [wobsoriano/vuetify-use-dialog#14]
I've observed that when using the confirmation in vuetify, the package causes the following error: 
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'classList')
    at Object.blockScrollStrategy [as block] (scrollStrategies.ts:85:22)
    at scrollStrategies.ts:57:47
    at EffectScope.run (chunk-FEPXYT3V.js:1291:20)
    at scrollStrategies.ts:53:27
```

It doesn't seem to affect the behavior, but it is noisy and might indicate bigger issues under the hood.

**Comment by wobsoriano** [comment]
Would love a basic repro!

**Comment by wobsoriano** [comment]
Hi, please install the latest version and let me know if your issue gets fixed. Thanks!
