### ISSUE TITLE
Nuxt - Rollup failed to resolve import 

### ISSUE THREAD

**Issue by torerik123** [wobsoriano/vuetify-use-dialog#20]
Trying to run npm run build and getting this error:

Nuxt Build Error: [vite]: Rollup failed to resolve import "/Users/wobsoriano/tmp/vuetify-use-dialog/node_modules/.pnpm/vuetify@3.4.7_typescript@5.3.3_vite-plugin-vuetify@2.0.1_vue@3.3.12/node_modules/vuetify/lib/framework.mjs" from "/Users/tor/INVID_DEV/invid-next/node_modules/vuetify-use-dialog/dist/vuetify-use-dialog.js".

**Comment by Zehir** [comment]
Looks like duplicate of #19

**Comment by wobsoriano** [comment]
Working on this!

**Comment by wobsoriano** [comment]
Let me know if v0.6.6 fixes this!

**Comment by Zehir** [comment]
> Let me know if v0.6.6 fixes this!

@wobsoriano it's does thanks
