### ISSUE TITLE
new dialogs open successive when press Enter

### ISSUE THREAD

**Issue by modos** [wobsoriano/vuetify-use-dialog#22]
After clicking the button, a dialog opens. When the "Enter" key is pressed, a new dialog opens and is placed on top of the previous one. This behavior can be observed on the demo page.

clicked on a delete button for first time:

![image](https://github.com/wobsoriano/vuetify-use-dialog/assets/15985332/fb4be5a5-5af1-41bd-a473-92a1393fc0a2)

then press enter:
![image](https://github.com/wobsoriano/vuetify-use-dialog/assets/15985332/007a4ee0-34e2-467a-8eab-ed780ff015df)

I believe the reason for this behavior is that the delete button remains focused after being clicked. To address this, we can manually disable the button or prevent the "Enter" key press using the "@keydown.enter.prevent" directive. Another option is to unfocus the button when it is clicked. However, i personally prefer not to make any changes and want library does it. is there any way to solve this built in?

**Comment by wobsoriano** [comment]
That is indeed annoying. This is likely caused by programmatically mounting a component to a newly created element. I'll look into this.
