### ISSUE TITLE
Closing the dialog by clicking on overlay makes it impossible to open it again

### ISSUE THREAD

**Issue by yakuz** [wobsoriano/vuetify-use-dialog#27]
### Describe the bug

When we close the dialog by clicking on the overlay, it doesn't reopen. It only works correctly when closed using the button.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-6cbrco?file=src%2Fcomponents%2FDemo.vue

### System Info

```bash
Vue 3.4.21, Vuetify 3.5.10
```

### Severity

annoyance

**Comment by huayuncc** [comment]
dialogProps: {persistent: true}

**Comment by yakuz** [comment]
> dialogProps: {persistent: true}

I understand, but I don't want to use this option. I want to still be able to close the window by clicking on the overlay, just like a regular v-dialog

**Comment by yakuz** [comment]
> dialogProps: {persistent: true}

I understand, but I don't want to use that option. I want to still be able to close the window by clicking on the overlay, just like a regular v-dialog because I'm using it in this case as a simple alert, without the option to choose ok/cancel.
