### ISSUE TITLE
useTheme must be called from inside a setup function

### ISSUE THREAD

**Issue by torerik123** [wobsoriano/vuetify-use-dialog#4]
I have a vuetify 2 project I am trying to migrate to v3.
In v2 I was using [vuetify-confirm](https://www.npmjs.com/package/vuetify-confirm)

In my v3 project I want to use vuetify-use-dialog in a plugin like this (similiar to vuetify-confirm):

 `this.$confirm(someProps).then(res => {  // .. Do stuff })`

But I am getting this error:
`Error: [Vuetify] useTheme must be called from inside a setup function`

Is it possible to achieve this functionality or is there an alternative way to implement it?

**Comment by RoduanKD** [comment]
+1 I'm facing this issue when I want to call useSnackbar from an Axios interceptor. or even when wraping it with a service call so I can DRY similar confirmations

**Comment by RoduanKD** [comment]
+1 I'm facing this issue when I want to call useSnackbar from an Axios interceptor. or even when wraping it with a service call so I can DRY similar confirmations

**Comment by wobsoriano** [comment]
@RoduanKD composables must be used inside a setup function

**Comment by wobsoriano** [comment]
@torerik123 added Options API support in v0.4.0.

```vue
<script lang="ts">
export default defineComponent({
  methods: {
    async handleConfirm() {
      const theme = 'dark' // theme is required

      const isConfirmed = await this.$confirm({ content: 'This action is permanent!', theme })

      if (!isConfirmed)
        return

      this.$toast({ text: 'Confirmed', theme })
    }
  }
})
</script>
```

For TS, you can use this to augment `$toast` and `$confirm`:

```ts
import { useConfirm, useSnackbar } from 'vuetify-use-dialog'

declare module 'vue' {
  interface ComponentCustomProperties {
    $confirm: typeof useConfirm
    $toast: typeof useSnackbar
  }
}
```

FYI, `theme` is required as I have no idea where to get values for this in the plugin. If you have an idea, please feel free to open a PR. You'll likely add it [here](https://github.com/wobsoriano/vuetify-use-dialog/blob/main/src/index.ts#L50)
