### ISSUE TITLE
CreateSnackbar blocks router.back?

### ISSUE THREAD

**Issue by FreezeNow** [wobsoriano/vuetify-use-dialog#8]
When i use CreateSnackbar, router.back stopped working for the time snackbar showed, but router.replace , router.push worked fine. 

This is very strange. Does anyone know what's going on?

**Comment by wobsoriano** [comment]
Weird. Do you get the same behavior when using plain vuetify snackbar?

**Comment by wobsoriano** [comment]
Please install latest version and let me know if it fixes your issue. Feel free to reopen!
